DROP TABLE athlete_events;

DROP TABLE countries5;

DROP TABLE noc_regions;

select * from customer_data

--- What is the total revenue generated by male vs. female customers?
   SELECT Gender, SUM([Purchase Amount (USD)]) AS total_revenue
	FROM customer_data
	GROUP BY Gender;

SELECT COLUMN_NAME
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'customer_data';

--- Which customers used a discount but still spent more than the average purchase amount?
 
 SELECT *
	FROM customer_data
	WHERE discount_applied = 'Yes'
	  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data);

  -- Which are the top 5 products with the highest average review rating?

  SELECT TOP 5 item_purchased, AVG(review_rating) AS avg_rating
	FROM customer_data
	GROUP BY item_purchased
	ORDER BY avg_rating DESC;


 ---Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount
	FROM customer_data
	WHERE shipping_type IN ('Standard', 'Express')
	GROUP BY shipping_type;

---Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       AVG(purchase_amount) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
	FROM customer_data
	GROUP BY subscription_status;


---Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_pct
	FROM customer_data
	GROUP BY item_purchased
	ORDER BY discount_pct DESC;

-- Segment customers into New, Returning, and Loyal based on total number of previous purchases.
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS num_customers,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer_data
GROUP BY
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END;

--- What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category, item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customer_data
    GROUP BY category, item_purchased
) ranked
WHERE rn <= 3;

---are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe 

select subscription_status,
	count(customer_id)as repeat_buyers
	from customer_data
	where previous_purchases > 5
	group by subscription_status;


---what is the revenue contribution of each age group?
select age,
	sum(purchase_amount)as total_revenue
	from customer_data
	group by age
	order by total_revenue desc;
